image: python:3.11

definitions:
  caches:
    local-dir: "~/.local"

pipelines:
  default:
    - step:
        name: Lint and test
        caches:
          - pip
          - local-dir
        script:
          - export PATH="$HOME/.local/bin:$PATH"
          - python3 -m pip install --user pipx==1.4.1
          - python3 -m pipx install poetry==1.7.1
          - poetry install --only lint
          - poetry run ruff check .
          - poetry install --with test
          - poetry run pytest -vvv --cov={{ cookiecutter.project_slug }} --junitxml=./test-reports/junit.xml tests
