image: python:3.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -U pip
          - pip install -r requirements.txt
          - py.test -vv tests
