{% if cookiecutter.use_conda == 'y' -%}
image: continuumio/miniconda3:4.9.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - conda env create -n {{ cookiecutter.package_name }} --file requirements/test.yml
          - conda activate {{ cookiecutter.package_name }}
          - pip install src/{{ cookiecutter.package_name }}
          - pytest -vvv --cov={{ cookiecutter.package_name }} tests
{% else -%}
image: python:3.9.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements/test.txt
          - pytest -vvv --cov={{ cookiecutter.package_name }} tests
{% endif -%}
